version: '3.1'

services:

  pg:
    container_name: pg
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gostack_desafio06_tests
    ports:
      - 5432:5432
